pipeline {
    agent {
        label {
            label "docker"
            //customWorkspace "/bitnami/jenkins/jenkins_home/jobs/ElasticBeanstalk_Pipeline/workspace_ebs/" 
        }
    }
    environment {
        NODE_ENV = 'local'
        NPM_AF6= credentials('7b37de90-52a1-4f07-b802-66faf02271ef')
    }

    stages {

        stage('install-dependencies') {

            agent {
                docker {
                    label 'docker'
                    image 'node:erbium-alpine'
                    args '-u root:root'
                }           
            }
            steps {
                configFileProvider([configFile(fileId: 'acf6139b-5d22-4447-a522-f55eef11efa7', targetLocation: '.npmrc')]) {
                sh 'npm --version'
                sh 'npm i -ddd'
                }
            }
        }

        stage('run-test'){
            agent {
                docker {
                    label 'docker'
                    image 'node:erbium-alpine'
                    args '-u root:root'
                } 
            }
            steps {
                sh 'npm run test'
            }
        }
        
        stage('publish-NPM') {
            agent {
                docker {
                    label 'docker'
                    image 'node:erbium-alpine'
                    args '-u root:root'
                }      
            }     
            steps {
                configFileProvider([configFile(fileId: 'acf6139b-5d22-4447-a522-f55eef11efa7', targetLocation: '.npmrc')]) {
                sh 'npm publish'
                }
            }
        }


    } //--end stages
}